apiVersion: apps/v1
kind: Deployment
metadata:
  name: save-name-deployment
  labels:
    app: save-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: save-name
  template:
    metadata:
      labels:
        app: save-name
    spec:
      containers:
      - name: save-name
        image: save-name:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
